In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow_hub as hub
import numpy as np
%matplotlib inline

In [21]:
df = pd.read_csv("data/question_embeddings0.csv")
df

0         1         2         3         4         5         6  \
0    -0.004167  0.003991 -0.063261  0.051590 -0.041000 -0.044420  0.084289   
1     0.028851 -0.046769 -0.003425  0.002011  0.038640  0.033116  0.003396   
2    -0.027575  0.065745 -0.046614 -0.042876 -0.006606 -0.022570 -0.026257   
3     0.011732  0.020154 -0.052613  0.025233 -0.056231 -0.056353  0.091451   
4     0.015800  0.015869 -0.042117 -0.056513  0.059205 -0.003981  0.005216   
5    -0.031953 -0.002469 -0.041008  0.024304  0.053117  0.003803  0.065083   
6    -0.017040  0.052235 -0.043022 -0.027080  0.010462  0.034135  0.075223   
7    -0.032157  0.034428 -0.023454  0.008774  0.013414  0.075705  0.031538   
8     0.008289 -0.024881 -0.014929 -0.015841  0.023373  0.045953  0.019825   
9    -0.018821  0.017218 -0.001502  0.013991  0.001999  0.042778  0.016658   
10   -0.054397  0.004405 -0.024746  0.064622  0.044663 -0.034714  0.039338   
11   -0.001095  0.038586 -0.084314  0.070829 -0.012941  0.027554  0.031617   
12    0.023836  0.019385 -0.047144  0.047299 -0.070703 -0.026370  0.096039   
13    0.058251 -0.021920 -0.037046 -0.058260  0.012969 -0.029978  0.016058   
14    0.034515 -0.015156 -0.044353  0.053828  0.060839 -0.067150 -0.003653   
15    0.030619 -0.028252 -0.028118 -0.022468 -0.079955 -0.021736  0.041344   
16    0.012315  0.053074 -0.022205 -0.020011  0.066704 -0.063855 -0.006269   
17   -0.048513  0.038268 -0.039777 -0.031951  0.012298  0.084846  0.001422   
18    0.074265 -0.023927 -0.039823  0.006029  0.029357 -0.037961  0.019289   
19   -0.021768 -0.058567 -0.034422  0.032917 -0.009271 -0.063565  0.101454   
20    0.028085  0.027305 -0.006991 -0.042194  0.046753  0.009589 -0.003278   
21    0.021661 -0.047109 -0.029041 -0.016934 -0.052257 -0.050292 -0.020247   
22    0.014773  0.019063 -0.074890 -0.007395 -0.046932 -0.022449  0.110818   
23   -0.034030  0.026103 -0.019423  0.016631 -0.011488 -0.031206  0.050606   
24   -0.046202  0.017870 -0.024039 -0.018389  0.008161 -0.002240  0.025201   
25    0.003370 -0.005913 -0.034238 -0.016837  0.063145  0.030146  0.002294   
26   -0.037866  0.002452 -0.014219  0.060395 -0.014592 -0.015618  0.100049   
27    0.014171 -0.065653 -0.020245  0.009294  0.009956 -0.085907 -0.007645   
28    0.015019 -0.036194 -0.007659 -0.014507  0.020973 -0.052306 -0.051698   
29    0.026002 -0.024976 -0.051838 -0.046355  0.040833 -0.023416  0.036530   
...        ...       ...       ...       ...       ...       ...       ...   
9970 -0.009491 -0.021919 -0.022187  0.050115 -0.045515 -0.067520  0.016860   
9971  0.051663  0.058362 -0.019957  0.032096 -0.009979 -0.059181  0.028273   
9972 -0.059313 -0.041024 -0.020233 -0.020669  0.026343 -0.031518  0.012089   
9973  0.043846 -0.026240 -0.031219  0.066561  0.054297  0.015629  0.077306   
9974 -0.027234 -0.076636 -0.028473 -0.046706  0.038278 -0.060956  0.076494   
9975  0.034395 -0.042579 -0.054871  0.029576  0.068753 -0.002069 -0.022651   
9976  0.035750 -0.007749 -0.028945 -0.007545  0.030785  0.045299 -0.013928   
9977 -0.026327  0.063418 -0.038249  0.052164  0.061357 -0.047484  0.050476   
9978 -0.036026 -0.031057 -0.050517 -0.084213  0.042688 -0.023111  0.039136   
9979  0.022847  0.031719 -0.054655  0.062217  0.056610 -0.056074 -0.005129   
9980 -0.066584  0.058355 -0.015967  0.052574  0.041303 -0.056615  0.012926   
9981 -0.063080 -0.076466 -0.031218  0.074429  0.002669 -0.088515  0.069518   
9982 -0.030644  0.001435 -0.019241  0.004732  0.009166 -0.025332  0.010734   
9983 -0.035428 -0.060025 -0.036412  0.045765  0.073935 -0.031157  0.038654   
9984  0.022616 -0.040842 -0.015559 -0.029237  0.003220 -0.058819 -0.006045   
9985  0.064592 -0.037348 -0.038360 -0.033099 -0.041040 -0.064767  0.002755   
9986  0.028667 -0.030361 -0.031771  0.048178  0.027232  0.017478 -0.003274   
9987  0.054631  0.065953 -0.020192 -0.045389  0.023379  0.010284  0.019992   
9988  0.004348 -0.070996 -0.026375 -0.017233  0.061170 -0.067266  0.076244   
9989  0.005042 -0.064050 -0.034534 

In [30]:
# read training data
train_df = pd.read_csv("data/train.csv")
print("Training Data Frame Dimensions: " + str(train_df.shape))

Training Data Frame Dimensions: (1306122, 3)


In [12]:
test = np.array([1,2,3,4])

In [18]:
test[2:4]

array([3, 4])

In [31]:
# first 5 elements of training data
train_df.head()

qid                                      question_text  \
0  00002165364db923c7e6  How did Quebec nationalists see their province...   
1  000032939017120e6e44  Do you have an adopted dog, how would you enco...   
2  0000412ca6e4628ce2cf  Why does velocity affect time? Does velocity a...   
3  000042bf85aa498cd78e  How did Otto von Guericke used the Magdeburg h...   
4  0000455dfa3e01eae3af  Can I convert montra helicon D to a mountain b...   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [32]:
# last 5 elements of training data
train_df.tail()

qid  \
1306117  ffffcc4e2331aaf1e41e   
1306118  ffffd431801e5a2f4861   
1306119  ffffd48fb36b63db010c   
1306120  ffffec519fa37cf60c78   
1306121  ffffed09fedb5088744a   

                                             question_text  target  
1306117  What other technical skills do you need as a c...       0  
1306118  Does MS in ECE have good job prospects in USA ...       0  
1306119                          Is foam insulation toxic?       0  
1306120  How can one start a research project based on ...       0  
1306121  Who wins in a battle between a Wolverine and a...       0

In [33]:
insincere_df = train_df.loc[train_df["target"] == 1]
print("The number of insincere is " + str(insincere_df.shape[0]))

The number of insincere is 80810


In [34]:
sincere_df = train_df.loc[train_df["target"] == 0]
print("The number of sincere is " + str(sincere_df.shape[0]))

The number of sincere is 1225312


In [42]:
# get numpy array of questions
questions = train_df["question_text"].values

In [57]:
test = questions[0:2]
test

array(['How did Quebec nationalists see their province as a nation in the 1960s?',
       'Do you have an adopted dog, how would you encourage people to adopt and not shop?'],
      dtype=object)

In [58]:
# Import the Universal Sentence Encoder's TF Hub module
module_url = "https://tfhub.dev/google/universal-sentence-encoder/2"
embed = hub.Module(module_url)

In [63]:
with tf.Session() as sess:
    sess.run([tf.global_variables_initializer(), tf.tables_initializer()])
    question_embeddings = sess.run(embed(test))
    print(question_embeddings)
    print(question_embeddings.shape)
    embedding_df = pd.DataFrame(question_embeddings)
    embedding_df.to_csv("test.csv", index=False)

INFO:tensorflow:Saver not created because there are no variables in the graph to restore
[[-0.00416658  0.00399125 -0.06326147 ... -0.04322257 -0.04416081
  -0.06633756]
 [ 0.028851   -0.04676896 -0.00342507 ...  0.05266976 -0.03536891
   0.00574462]]
(2, 512)


In [64]:
pd.read_csv("test.csv")

0         1         2         3        4         5         6  \
0 -0.004167  0.003991 -0.063261  0.051590 -0.04100 -0.044420  0.084289   
1  0.028851 -0.046769 -0.003425  0.002011  0.03864  0.033116  0.003396   

          7         8         9    ...          502       503       504  \
0 -0.007363 -0.021403 -0.022497    ...     0.060429 -0.062331 -0.017937   
1  0.041565 -0.004693  0.022073    ...     0.045903  0.027739 -0.002885   

        505       506       507       508       509       510       511  
0 -0.033932  0.009563 -0.063174  0.053774 -0.043223 -0.044161 -0.066338  
1  0.001373 -0.040582 -0.004657  0.026895  0.052670 -0.035369  0.005745  

[2 rows x 512 columns]

In [67]:
tf.__version__

'1.10.0'

In [68]:
pd.read_csv("test_real.csv")

0         1         2         3        4         5         6  \
0 -0.004167  0.003991 -0.063261  0.051590 -0.04100 -0.044420  0.084289   
1  0.028851 -0.046769 -0.003425  0.002011  0.03864  0.033116  0.003396   

          7         8         9    ...          502       503       504  \
0 -0.007363 -0.021403 -0.022497    ...     0.060429 -0.062331 -0.017937   
1  0.041565 -0.004693  0.022073    ...     0.045903  0.027739 -0.002885   

        505       506       507       508       509       510       511  
0 -0.033932  0.009563 -0.063174  0.053774 -0.043223 -0.044161 -0.066338  
1  0.001373 -0.040582 -0.004657  0.026895  0.052670 -0.035369  0.005745  

[2 rows x 512 columns]

In [82]:
from keras.models import Model
from keras.layers import Input, Dense, Activation

In [83]:
X = Input(shape=(512,))
hidden1 = Dense(units=1024, activation='relu')(X)
hidden2 = Dense(units=512, activation='relu')(hidden1)
hidden3 = Dense(units=256, activation='relu')(hidden2)
output = Dense(units=1, activation='sigmoid')(hidden3)
model = Model(inputs=X, outputs=output)
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 512)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 1024)              525312    
_________________________________________________________________
dense_6 (Dense)              (None, 512)               524800    
_________________________________________________________________
dense_7 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 257       
Total params: 1,181,697
Trainable params: 1,181,697
Non-trainable params: 0
_________________________________________________________________


In [84]:
# generate random training data
x_train = np.random.random((100000, 512))
y_train = np.random.randint(2, size=(100000, 1))

In [ ]:
model.fit(x_train, y_train, epochs=20)

Epoch 1/20
100000/100000 [==============================] - 51s 515us/step - loss: 0.6938 - acc: 0.4999
Epoch 2/20
100000/100000 [==============================] - 40s 404us/step - loss: 0.6932 - acc: 0.4995
Epoch 3/20
100000/100000 [==============================] - 40s 404us/step - loss: 0.6933 - acc: 0.4990
Epoch 4/20
 17728/100000 [====>.........................] - ETA: 32s - loss: 0.6932 - acc: 0.5013

In [78]:
np.sum((model.predict(x_train) >= 0.5) == y_train)

910

In [80]:
(model.predict(x_train) >= 0.5)[0:5]

array([[ True],
       [ True],
       [False],
       [False],
       [ True]])

In [81]:
y_train[0:5]

array([[1],
       [1],
       [0],
       [0],
       [1]])