In [26]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import keras
import os
import numpy as np
%matplotlib inline

In [27]:
# read training data
train_df = pd.read_csv("data/train.csv")
print("Training Data Frame Dimensions: " + str(train_df.shape))

Training Data Frame Dimensions: (1306122, 3)


In [28]:
# first 5 elements of training data
train_df.head()

qid                                      question_text  \
0  00002165364db923c7e6  How did Quebec nationalists see their province...   
1  000032939017120e6e44  Do you have an adopted dog, how would you enco...   
2  0000412ca6e4628ce2cf  Why does velocity affect time? Does velocity a...   
3  000042bf85aa498cd78e  How did Otto von Guericke used the Magdeburg h...   
4  0000455dfa3e01eae3af  Can I convert montra helicon D to a mountain b...   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [29]:
# last 5 elements of training data
train_df.tail()

qid  \
1306117  ffffcc4e2331aaf1e41e   
1306118  ffffd431801e5a2f4861   
1306119  ffffd48fb36b63db010c   
1306120  ffffec519fa37cf60c78   
1306121  ffffed09fedb5088744a   

                                             question_text  target  
1306117  What other technical skills do you need as a c...       0  
1306118  Does MS in ECE have good job prospects in USA ...       0  
1306119                          Is foam insulation toxic?       0  
1306120  How can one start a research project based on ...       0  
1306121  Who wins in a battle between a Wolverine and a...       0

In [30]:
# read test data
test_df = pd.read_csv("data/train.csv")
print("Test Data Frame Dimensions: " + str(test_df.shape))

Test Data Frame Dimensions: (1306122, 3)


In [31]:
test_df.head()

qid                                      question_text  \
0  00002165364db923c7e6  How did Quebec nationalists see their province...   
1  000032939017120e6e44  Do you have an adopted dog, how would you enco...   
2  0000412ca6e4628ce2cf  Why does velocity affect time? Does velocity a...   
3  000042bf85aa498cd78e  How did Otto von Guericke used the Magdeburg h...   
4  0000455dfa3e01eae3af  Can I convert montra helicon D to a mountain b...   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [32]:
test_df.tail()

qid  \
1306117  ffffcc4e2331aaf1e41e   
1306118  ffffd431801e5a2f4861   
1306119  ffffd48fb36b63db010c   
1306120  ffffec519fa37cf60c78   
1306121  ffffed09fedb5088744a   

                                             question_text  target  
1306117  What other technical skills do you need as a c...       0  
1306118  Does MS in ECE have good job prospects in USA ...       0  
1306119                          Is foam insulation toxic?       0  
1306120  How can one start a research project based on ...       0  
1306121  Who wins in a battle between a Wolverine and a...       0

In [42]:
# Generate dummy data
import numpy as np

labels = np.random.randint(2, size=(1000, 1))
data = np.random.random((1000, 512))
test = data
results = labels

In [47]:
print(data)

[[0.85314064 0.09459427 0.77902909 ... 0.30016484 0.12092971 0.91058521]
 [0.69265633 0.91436831 0.38139414 ... 0.38265083 0.7028286  0.05930205]
 [0.80646502 0.49092206 0.2074234  ... 0.19946205 0.01187369 0.80270837]
 ...
 [0.3917083  0.41233252 0.59315065 ... 0.66575081 0.99449461 0.96517336]
 [0.22466286 0.41064903 0.97671977 ... 0.22063949 0.954963   0.03142363]
 [0.09900612 0.13169242 0.58193975 ... 0.04142291 0.4177496  0.57039056]]


In [43]:
#  keras sequential garbage
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential()
model.add(Dense(512, activation='relu', input_dim=512))
model.add(Dense(1024, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam',
              loss='binary_crossentropy', metrics=['accuracy'])



model.summary()
# Train the model, iterating on the data in batches of 32 samples
model.fit(test, results, epochs=30, batch_size=1000)


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_29 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_30 (Dense)             (None, 1024)              525312    
_________________________________________________________________
dense_31 (Dense)             (None, 256)               262400    
_________________________________________________________________
dense_32 (Dense)             (None, 1)                 257       
Total params: 1,050,625
Trainable params: 1,050,625
Non-trainable params: 0
_________________________________________________________________
Epoch 1/30
1000/1000 [==============================] - 1s 519us/step - loss: 0.7271 - acc: 0.5050
Epoch 2/30
1000/1000 [==============================] - 0s 38us/step - loss: 1.4721 - acc: 0.4950
Epoch 3/30
1000/1000 [==============================] - 0s 40us/ste

In [44]:
np.sum((model.predict(test)>= 0.5) == results)

674